version: 1
disable_existing_loggers: False
formatters: 
    generic: 
        class: logging.Formatter
        format: '%(asctime)s [%(process)d] [%(levelname)s] %(message)s'
        datefmt: '%Y-%m-%d %H:%M:%S %z'
handlers: 
    console: 
        class: logging.StreamHandler
        formatter: generic
        stream: ext://sys.stdout
    std_file: 
        class: logging.FileHandler
        formatter: generic
        filename: ./logs/stdout.log
    err_file: 
        class: logging.FileHandler
        formatter: generic
        filename: ./logs/errout.log
loggers:
    error: 
        level: ERROR
        handlers: [console, err_file]
        propagate: True
    main: 
        level: INFO
        handlers: [console, std_file]
        propagate: True
root:
     level: INFO
     handlers: [console, std_file]
    
